version: '3'
services:
  openldap:
    build:
      dockerfile: Dockerfile-ldap
      context: .
    environment:
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: ${READER_UID}
      LDAP_READONLY_USER_PASSWORD: ${READER_PASS}
    networks:
      ldap-backend:
        aliases:
          - ldap

  python:
    build:
      dockerfile: Dockerfile-python
      context: .
    environment:
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ..:/work
    depends_on:
      - openldap
    networks:
      ldap-backend:

  phpldapadmin:
    image: osixia/phpldapadmin
    ports:
      - "8080:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS=false:
    depends_on:
      - openldap
    networks:
      ldap-backend:

networks:
  ldap-backend:
