version: '3'
services:
  openldap:
    # We need an image with LDAP that is aware of the postfix schema.
    image: jsmitsnl/docker-openldap-postfix-book
    environment:
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${CONFIG_PASSWORD}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: ${READER_UID}
      LDAP_READONLY_USER_PASSWORD: ${READER_PASS}

  python:
    build:
      dockerfile: Dockerfile-python
      context: .
    environment:
      LDAP_DOMAIN: ${DOMAIN}
      LDAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ..:/work
    links:
      - openldap:ldap
